spring:
  application:
    name: project_clothes
  datasource:
    url: jdbc:mysql://localhost:3306/project_clothes
    username: root
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: dinhxuantruong2003coi@gmail.com
    password: ttqx dwgn usym nsep
    properties:
      mail:
        auth:
        starttls:
          enable: true
    default-encoding: UTF-8
server:
  port: 8080
cloudinary:
  cloud-name: mediaflows_6af05438-6dd4-44bb-a568-abb4cdcd05c5
  api-key: 812641888779897
  api-secret: Ws0ewkeYl1ipBUud-AnkPahcF-w
logging:
  level:
    org.springframework: INFO
    com.t3h.projectclothes: DEBUG

app:
  jwt:
    # Chuỗi secret base64 cho JWT, có thể thay bằng chuỗi khác mạnh hơn
    secret: VGhpcy1pcy1hLXNpbXBsZS1qd3Qtc2VjcmV0LXNob3VsZC1iZS1iYXNlNjQ=
    # Thời gian sống của token (millisecond) - 1 ngày
    expiration-ms: 86400000
